# Generated by Django 3.1.6 on 2021-02-05 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 5, 18, 51, 40, 401955))),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 5, 18, 51, 40, 402955))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practice.department')),
            ],
        ),
    ]
