# Generated by Django 3.1.6 on 2021-02-05 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 18, 53, 42, 457223)),
        ),
        migrations.AlterField(
            model_name='team',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 18, 53, 42, 457223)),
        ),
    ]
