# Generated by Django 3.1.6 on 2021-02-05 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0002_auto_20210205_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 5, 18, 59, 33, 215555))),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 18, 59, 33, 215555)),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practice.department'),
        ),
    ]
